### ISSUE TITLE
AttributeError: 'CustomHTTPClient' object has no attribute '_session'

### ISSUE THREAD

**Issue by Himan000** [joowani/python-arango#111]
Hi @joowani ,
when upgrade python-arango from 4.4.0 to 5.1.0 and use the CustomHTTPClient code in [https://python-driver-for-arangodb.readthedocs.io/en/5.0.0/http.html](https://python-driver-for-arangodb.readthedocs.io/en/5.0.0/http.html), error occur as title. Is this a bug ?

```
  File "D:\project\python\project_1\util\CustomHTTPClient.py", line 25, in create_session
    self._session.mount('https://', adapter)
AttributeError: 'CustomHTTPClient' object has no attribute '_session'
```

**Comment by Himan000** [comment]
Hi @joowani ,
I know the reason.

```
def create_session(self, host):
        session = Session()

        # Add request header.
        session.headers.update({'x-my-header': 'true'})

        # Enable retries.
        adapter = HTTPAdapter(max_retries=5)
        self._session.mount('https://', adapter) # **should be session.mount('https://', adapter)**

        return session
```

Thanks and I will close this issue.
